sudo: required
dist: trusty
#sudo: false

#apt:
#  sources:

install:
  #- sudo add-apt-repository -y ppa:texlive-backports/ppa
  - sudo apt-get update
  - sudo apt-get install -y texlive-full

script:
  - pdflatex -interaction=nonstopmode conteq.dtx
  - makeindex -s gglo.ist -o conteq.gls conteq.glo
  - pdflatex -interaction=nonstopmode conteq.dtx
